added new fonts, styled all page subheadings
Delta-Unleashed/paw-spot pull request #38
Opened 2022-08-26 23:07 UTC by wasegree

2022-08-26 23:16 UTC, triciasykes requested changes
there's a lot of commented out code....

2022-08-26 23:18 UTC, elysemontano requested changes
A few small things to remove

2022-08-26 23:18 UTC, elysemontano commented on app/assets/stylesheets/application.scss
> +// }
Please remove commented out code

2022-08-26 23:18 UTC, elysemontano commented on app/javascript/components/pages/Home.js
> +                    // caption: 'Slide 1',
Is this needed?  (This appears multiple times on this page, so please address this for all of those).  Please remove or uncomment

2022-08-26 23:22 UTC, elysemontano approved these changes

2022-08-29 15:51 UTC, triciasykes approved these changes

2022-08-29 16:13 UTC, merged